# Generated by Django 4.1.7 on 2023-05-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
