# Generated by Django 4.1.7 on 2023-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
