# Generated by Django 4.1.7 on 2023-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_products_sum_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
